name: brick
description: "A new Flutter project."

publish_to: "none"

version: 1.0.01+1001

environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_fadein: ^2.0.0
  flutter_localization: ^0.2.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.3
  intl: ^0.19.0
  scroll_edge_listener: ^0.1.1
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: nrt
  #     fonts:
  #       - asset: assets/font/nrt/nrt_reg.ttf
  #         weight: 300
flutter_gen:
  integrations:
    flutter_svg: true
